### ISSUE TITLE
Edit search list to make it fit the css more

### ISSUE THREAD

**Issue by mamamia5x** [mamamia5x/markdownpedia#20]
The search looks like this
![image](https://user-images.githubusercontent.com/57536929/106286019-cccb4280-620a-11eb-8bc3-26a0043ebbf5.png)

But it just doesn't fit.

Maybe it is the font color and size, or the style of the lists.

But if you want to edit the list to make it fit, you'd just need to edit this
```css
  #listOfItems {
  font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
  /* Remove default list styling */
  list-style-type: none;
  padding: 0;
  margin: 0;
}

#listOfItems li a {
  border: 1px solid #ddd; /* Add a border to all links */
  margin-top: -1px; /* Prevent double borders */
  background-color: #f6f6f6; /* Grey background color */
  padding: 12px; /* Add some padding */
  text-decoration: none; /* Remove default text underline */
  font-size: 18px; /* Increase the font-size */
  color: black; /* Add a black text color */
  display: block; /* Make it into a block element to fill the whole list */
}

#listOfItems li a:hover:not(.header) {
  background-color: #eee; /* Add a hover effect to all links, except for headers */
}
```
And it's found in vital/pages/search/index.html
You'll just need to edit this page if you'd like to see what it looks like, but to make a permanent you'll need to copy the changes
and paste them to vital/searchtemplate.html
